name: Test

on:
  push:
    branches-ignore:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Test
        run: dotnet test HousingPricePredictor.slnx --configuration Release --verbosity normal
